/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Mon Jan 29 16:46:27 2018. */

#include "BroJoystick.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t BroJoystick_LeftJoy_X_default = 512u;
const uint32_t BroJoystick_LeftJoy_Y_default = 512u;
const uint32_t BroJoystick_RightJoy_X_default = 512u;
const uint32_t BroJoystick_RightJoy_Y_default = 512u;
const uint32_t BroJoystick_LeftSlider_default = 0u;
const uint32_t BroJoystick_RightSlider_default = 0u;
const bool BroJoystick_LeftJoy_Btn_default = false;
const bool BroJoystick_RightJoy_Btn_default = false;
const bool BroJoystick_btn1_default = false;
const bool BroJoystick_btn2_default = false;
const bool BroJoystick_btn3_default = false;
const bool BroJoystick_btn4_default = false;
const bool BroJoystick_sw1_default = false;
const bool BroJoystick_sw2_default = false;
const bool BroJoystick_sw3_default = false;
const bool BroJoystick_sw4_default = false;


const pb_field_t BroJoystick_fields[17] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, BroJoystick, LeftJoy_X, LeftJoy_X, &BroJoystick_LeftJoy_X_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, LeftJoy_Y, LeftJoy_X, &BroJoystick_LeftJoy_Y_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, RightJoy_X, LeftJoy_Y, &BroJoystick_RightJoy_X_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, RightJoy_Y, RightJoy_X, &BroJoystick_RightJoy_Y_default),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, LeftSlider, RightJoy_Y, &BroJoystick_LeftSlider_default),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, RightSlider, LeftSlider, &BroJoystick_RightSlider_default),
    PB_FIELD(  7, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, LeftJoy_Btn, RightSlider, &BroJoystick_LeftJoy_Btn_default),
    PB_FIELD(  8, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, RightJoy_Btn, LeftJoy_Btn, &BroJoystick_RightJoy_Btn_default),
    PB_FIELD(  9, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, btn1, RightJoy_Btn, &BroJoystick_btn1_default),
    PB_FIELD( 10, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, btn2, btn1, &BroJoystick_btn2_default),
    PB_FIELD( 11, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, btn3, btn2, &BroJoystick_btn3_default),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, btn4, btn3, &BroJoystick_btn4_default),
    PB_FIELD( 13, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, sw1, btn4, &BroJoystick_sw1_default),
    PB_FIELD( 14, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, sw2, sw1, &BroJoystick_sw2_default),
    PB_FIELD( 15, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, sw3, sw2, &BroJoystick_sw3_default),
    PB_FIELD( 16, BOOL    , REQUIRED, STATIC  , OTHER, BroJoystick, sw4, sw3, &BroJoystick_sw4_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
