/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Apr 13 12:30:02 2017. */

#include "BroJoystick.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool BroJoystick_btn1_default = false;
const bool BroJoystick_btn2_default = false;
const bool BroJoystick_btn4_default = false;
const bool BroJoystick_btn5_default = false;
const bool BroJoystick_sw1_default = false;
const bool BroJoystick_sw2_default = false;
const bool BroJoystick_sw3_default = false;
const bool BroJoystick_sw4_default = false;


const pb_field_t BroJoystick_fields[13] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, BroJoystick, LeftJoy_X, LeftJoy_X, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, LeftJoy_Y, LeftJoy_X, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, RightJoy_X, LeftJoy_Y, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, BroJoystick, RightJoy_Y, RightJoy_X, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, btn1, RightJoy_Y, &BroJoystick_btn1_default),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, btn2, btn1, &BroJoystick_btn2_default),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, btn4, btn2, &BroJoystick_btn4_default),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, btn5, btn4, &BroJoystick_btn5_default),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, sw1, btn5, &BroJoystick_sw1_default),
    PB_FIELD( 10, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, sw2, sw1, &BroJoystick_sw2_default),
    PB_FIELD( 11, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, sw3, sw2, &BroJoystick_sw3_default),
    PB_FIELD( 12, BOOL    , OPTIONAL, STATIC  , OTHER, BroJoystick, sw4, sw3, &BroJoystick_sw4_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
