/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Mon Jan 29 16:46:27 2018. */

#ifndef PB_BROJOYSTICK_PB_H_INCLUDED
#define PB_BROJOYSTICK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BroJoystick {
    uint32_t LeftJoy_X;
    uint32_t LeftJoy_Y;
    uint32_t RightJoy_X;
    uint32_t RightJoy_Y;
    uint32_t LeftSlider;
    uint32_t RightSlider;
    bool LeftJoy_Btn;
    bool RightJoy_Btn;
    bool btn1;
    bool btn2;
    bool btn3;
    bool btn4;
    bool sw1;
    bool sw2;
    bool sw3;
    bool sw4;
/* @@protoc_insertion_point(struct:BroJoystick) */
} BroJoystick;

/* Default values for struct fields */
extern const uint32_t BroJoystick_LeftJoy_X_default;
extern const uint32_t BroJoystick_LeftJoy_Y_default;
extern const uint32_t BroJoystick_RightJoy_X_default;
extern const uint32_t BroJoystick_RightJoy_Y_default;
extern const uint32_t BroJoystick_LeftSlider_default;
extern const uint32_t BroJoystick_RightSlider_default;
extern const bool BroJoystick_LeftJoy_Btn_default;
extern const bool BroJoystick_RightJoy_Btn_default;
extern const bool BroJoystick_btn1_default;
extern const bool BroJoystick_btn2_default;
extern const bool BroJoystick_btn3_default;
extern const bool BroJoystick_btn4_default;
extern const bool BroJoystick_sw1_default;
extern const bool BroJoystick_sw2_default;
extern const bool BroJoystick_sw3_default;
extern const bool BroJoystick_sw4_default;

/* Initializer values for message structs */
#define BroJoystick_init_default                 {512u, 512u, 512u, 512u, 0u, 0u, false, false, false, false, false, false, false, false, false, false}
#define BroJoystick_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BroJoystick_LeftJoy_X_tag                1
#define BroJoystick_LeftJoy_Y_tag                2
#define BroJoystick_RightJoy_X_tag               3
#define BroJoystick_RightJoy_Y_tag               4
#define BroJoystick_LeftSlider_tag               5
#define BroJoystick_RightSlider_tag              6
#define BroJoystick_LeftJoy_Btn_tag              7
#define BroJoystick_RightJoy_Btn_tag             8
#define BroJoystick_btn1_tag                     9
#define BroJoystick_btn2_tag                     10
#define BroJoystick_btn3_tag                     11
#define BroJoystick_btn4_tag                     12
#define BroJoystick_sw1_tag                      13
#define BroJoystick_sw2_tag                      14
#define BroJoystick_sw3_tag                      15
#define BroJoystick_sw4_tag                      16

/* Struct field encoding specification for nanopb */
extern const pb_field_t BroJoystick_fields[17];

/* Maximum encoded size of messages (where known) */
#define BroJoystick_size                         57

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BROJOYSTICK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
