/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Thu Apr 13 12:30:02 2017. */

#ifndef PB_BROJOYSTICK_PB_H_INCLUDED
#define PB_BROJOYSTICK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BroJoystick {
    uint32_t LeftJoy_X;
    uint32_t LeftJoy_Y;
    uint32_t RightJoy_X;
    uint32_t RightJoy_Y;
    bool has_btn1;
    bool btn1;
    bool has_btn2;
    bool btn2;
    bool has_btn4;
    bool btn4;
    bool has_btn5;
    bool btn5;
    bool has_sw1;
    bool sw1;
    bool has_sw2;
    bool sw2;
    bool has_sw3;
    bool sw3;
    bool has_sw4;
    bool sw4;
/* @@protoc_insertion_point(struct:BroJoystick) */
} BroJoystick;

/* Default values for struct fields */
extern const bool BroJoystick_btn1_default;
extern const bool BroJoystick_btn2_default;
extern const bool BroJoystick_btn4_default;
extern const bool BroJoystick_btn5_default;
extern const bool BroJoystick_sw1_default;
extern const bool BroJoystick_sw2_default;
extern const bool BroJoystick_sw3_default;
extern const bool BroJoystick_sw4_default;

/* Initializer values for message structs */
#define BroJoystick_init_default                 {0, 0, 0, 0, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false}
#define BroJoystick_init_zero                    {0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BroJoystick_LeftJoy_X_tag                1
#define BroJoystick_LeftJoy_Y_tag                2
#define BroJoystick_RightJoy_X_tag               3
#define BroJoystick_RightJoy_Y_tag               4
#define BroJoystick_btn1_tag                     5
#define BroJoystick_btn2_tag                     6
#define BroJoystick_btn4_tag                     7
#define BroJoystick_btn5_tag                     8
#define BroJoystick_sw1_tag                      9
#define BroJoystick_sw2_tag                      10
#define BroJoystick_sw3_tag                      11
#define BroJoystick_sw4_tag                      12

/* Struct field encoding specification for nanopb */
extern const pb_field_t BroJoystick_fields[13];

/* Maximum encoded size of messages (where known) */
#define BroJoystick_size                         40

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BROJOYSTICK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
